USE sales_customer;
SELECT * FROM mytable;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue FROM mytable GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id FROM mytable WHERE discount_applied='Yes' AND purchase_amount>(SELECT AVG(purchase_amount) FROM mytable);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased FROM mytable GROUP BY item_purchased ORDER BY AVG(review_rating) DESC LIMIT 5 ;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, AVG(purchase_amount) AS average_amount FROM mytable WHERE shipping_type IN ('Standard','Express') GROUP BY shipping_type ;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, AVG(purchase_amount) AS average_amount, SUM(purchase_amount) AS total_revenue FROM mytable GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)*100/COUNT(*) AS percentage_discount FROM mytable GROUP BY 
item_purchased ORDER BY percentage_discount DESC LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT 'New' AS segment, SUM(CASE WHEN previous_purchases<(SELECT MAX(previous_purchases)/3 FROM mytable) THEN 1 ELSE 0 END) AS count FROM mytable 
UNION
SELECT 'Returning', SUM(CASE WHEN previous_purchases>=(SELECT MAX(previous_purchases)/3 FROM mytable) AND previous_purchases<=(SELECT 
2*MAX(previous_purchases)/3 FROM mytable) THEN 1 ELSE 0 END) AS count FROM mytable
UNION 
SELECT 'Loyal', SUM(CASE WHEN previous_purchases>(SELECT 2*MAX(previous_purchases)/3 FROM mytable) THEN 1 ELSE 0 END) AS count FROM mytable;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3; 

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers FROM mytable WHERE previous_purchases > 5 GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) AS total_revenue FROM mytable GROUP BY age_group;



